### ISSUE TITLE
Github tags

### ISSUE THREAD

**Issue by jayvdb** [iheyunfei/lets_find_up#1]
Could you create a tag at https://github.com/hyf0/lets_find_up/tags for the release on crates.io . Cheers, John

**Comment by hyfdev** [comment]
Thanks for reminding me. I haven't used this. Since the repo is going to be archived, I would do as you said in https://github.com/hyf0/sugar_path/issues/11.

**Comment by jayvdb** [comment]
I've done a new release of 0.0.2 and tagged it.
