### ISSUE TITLE
Uses deprecated crate nodejs_path

### ISSUE THREAD

**Issue by jayvdb** [iheyunfei/lets_find_up#2]
https://crates.io/crates/nodejs_path is https://github.com/hyf0/rusty_nodejs_path which is archived, and recommends using https://github.com/hyf0/sugar_path instead

**Comment by hyfdev** [comment]
Thanks for issuing. I'm going to archive this project too. Writing and maintaining a performant `
lets_find_up` need a lot of time which I currently lack.

**Comment by jayvdb** [comment]
If you like, you can transfer the project to me to maintain. I need a crate like this, couldnt find any other, and this one just needs the usual amount of up-keep.

**Comment by hyfdev** [comment]
Thank you. I would transfer the repo to you and add you as the owner of the crate.

**Comment by hyfdev** [comment]
@jayvdb You might need to rename or delete https://github.com/jayvdb/lets_find_up. 
![image](https://user-images.githubusercontent.com/49502170/218679311-55d30b34-d518-408c-8b61-e1983a6c4707.png)

PS: I have added you as the owner of the crate, you might need to check the email box.

**Comment by jayvdb** [comment]
Accepted crate , and I've deleted my fork

**Comment by hyfdev** [comment]
Done. I have sent the transfer request.

**Comment by jayvdb** [comment]
Fixed in https://github.com/jayvdb/lets_find_up/releases/tag/v0.0.3
